# Generated by Django 5.1.1 on 2024-11-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idioma',
            field=models.CharField(choices=[('pt-br', 'Português - Brasil'), ('eng', 'Inglês (Indisponível)')], default='pt-br', max_length=7, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
