# Generated by Django 5.1.1 on 2024-11-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='data',
            field=models.DateField(),
        ),
    ]
